[package]
name = "lib_tester"
version = "0.1.0"
edition = "2018"

[Build]
target = "aarch64-apple-darwin"
#target = ["x86_64-unknown-linux-gnu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
learn_lib = { path="../learn_lib" }